### ISSUE TITLE
无法启动游戏

### ISSUE THREAD

**Issue by YuYue-Amatsuki** [ThinkingStudios/Tweakeroo-Forge#2]
游戏版本：1.16.5
Forge版本：36.2.39
启动器提示注入失败
![image](https://github.com/ThinkingStudios/Tweakeroo-Forge/assets/86163024/8eec6887-bcb5-4d6f-adf4-22047db3ffa5)

日志如下：
```Java
[247��2023 21:03:17.007] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, FluidicBongo180, --version, 1.16.5-Forge_36.2.39, --gameDir, I:\.minecraft\versions\1.16.5-Forge_36.2.39, --assetsDir, I:\.minecraft\assets, --assetIndex, 1.16, --uuid, 2f8f8d043fbd49c4b1ef968cc7526843, --accessToken, ????????, --userType, msa, --versionType, PCL, --width, 854, --height, 480, --launchTarget, fmlclient, --fml.forgeVersion, 36.2.39, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550, --server, 192.168.1.5, --port, 25565]
[247��2023 21:03:17.023] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 11.0.16.1 by Oracle Corporation
[247��2023 21:03:18.187] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[247��2023 21:03:18.292] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/I:/.minecraft/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=CLIENT
[247��2023 21:03:21.154] [main/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[247��2023 21:03:21.359] [main/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[247��2023 21:03:21.367] [main/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[247��2023 21:03:21.375] [main/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[247��2023 21:03:21.381] [main/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[247��2023 21:03:21.384] [main/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[247��2023 21:03:21.384] [main/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[247��2023 21:03:21.397] [main/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[247��2023 21:03:21.397] [main/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[247��2023 21:03:21.414] [main/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[247��2023 21:03:21.426] [main/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[247��2023 21:03:21.432] [main/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[247��2023 21:03:23.702] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [icyllis.modernui.forge.MixinConnector]
[247��2023 21:03:23.702] [main/INFO] [mixin/]: Compatibility level set to JAVA_11
[247��2023 21:03:23.717] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, 1.16.5-Forge_36.2.39, --gameDir, I:\.minecraft\versions\1.16.5-Forge_36.2.39, --assetsDir, I:\.minecraft\assets, --uuid, 2f8f8d043fbd49c4b1ef968cc7526843, --username, FluidicBongo180, --assetIndex, 1.16, --accessToken, ????????, --userType, msa, --versionType, PCL, --width, 854, --height, 480, --server, 192.168.1.5, --port, 25565]
[247��2023 21:03:23.748] [main/INFO] [Rubidium/]: Loaded configuration file for Rubidium: 30 options available, 0 override(s) found
[247��2023 21:03:23.780] [main/WARN] [mixin/]: Reference map 'yuoenchants.refmap.json' for endless.mixins.json could not be read. If this is a development environment you can ignore this message
[247��2023 21:03:23.842] [main/INFO] [Sodium Extra Config/]: Loaded configuration file for Sodium Extra: 30 options available, 0 override(s) found
[247��2023 21:03:24.483] [main/INFO] [net.minecraftforge.coremod.CoreMod.observerlib/COREMODLOG]: Adding 'on_block_change' ASM patch...
[247��2023 21:03:24.592] [main/INFO] [net.minecraftforge.coremod.CoreMod.observerlib/COREMODLOG]: Added 'on_block_change' ASM patch!
[247��2023 21:03:26.264] [main/WARN] [IMixinConfigPlugin/]: Inventory Profiles Next: Doing our own dependency resolving! Because Forge is being Forge....: https://github.com/MinecraftForge/MinecraftForge/issues/9088
[247��2023 21:03:26.280] [main/WARN] [mixin/]: Error loading class: de/maxhenkel/easyvillagers/blocks/tileentity/TraderTileentityBase (java.lang.ClassNotFoundException: null)
[247��2023 21:03:26.280] [main/WARN] [mixin/]: @Mixin target de.maxhenkel.easyvillagers.blocks.tileentity.TraderTileentityBase was not found mixins.ipnext.json:MixinTraderTileEntityBase
[247��2023 21:03:28.860] [pool-3-thread-1/INFO] [net.minecraftforge.coremod.CoreMod.observerlib/COREMODLOG]: Adding 'on_block_change' ASM patch...
[247��2023 21:03:28.868] [pool-3-thread-1/INFO] [net.minecraftforge.coremod.CoreMod.observerlib/COREMODLOG]: Added 'on_block_change' ASM patch!
[247��2023 21:03:28.893] [pool-3-thread-1/FATAL] [mixin/]: Mixin apply failed tweakeroo.mixins.json:MixinWorld -> net.minecraft.world.World: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow field unloadedBlockEntities was not located in the target class net.minecraft.world.World. Using refmap Tweakerge-refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field unloadedBlockEntities was not located in the target class net.minecraft.world.World. Using refmap Tweakerge-refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:629) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:305) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:280) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1288) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154) ~[modlauncher-8.1.3.jar:8.1.3+8.1.3+main-8.1.x.c94d18ec]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.1.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.minecraft.block.Blocks.<clinit>(Blocks.java:30) ~[?:?]
	at net.minecraft.world.gen.surfacebuilders.SurfaceBuilder.<clinit>(SurfaceBuilder.java:12) ~[?:?]
	at net.minecraft.world.gen.surfacebuilders.ConfiguredSurfaceBuilders.<clinit>(SourceFile:11) ~[?:?]
	at net.minecraft.util.registry.WorldGenRegistries.func_243674_g(WorldGenRegistries.java:33) ~[?:?]
	at net.minecraft.util.registry.WorldGenRegistries.func_243668_a(WorldGenRegistries.java:89) ~[?:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[?:?]
	at net.minecraft.util.registry.WorldGenRegistries.<clinit>(WorldGenRegistries.java:88) ~[?:?]
	at net.minecraft.util.registry.Registry.<clinit>(Registry.java:464) ~[?:?]
	at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:38) ~[?:?]
	at net.minecraft.client.main.Main.lambda$main$0(Main.java:123) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: java.lang.reflect.InvocationTargetException
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at oolloo.jlw.Wrapper.main(Wrapper.java:53)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]: Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]: 	... 6 more
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: Caused by: java.lang.reflect.InvocationTargetException
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	... 10 more
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]: Caused by: java.lang.RuntimeException: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]: 	at net.minecraftforge.fml.loading.BackgroundWaiter.runAndTick(BackgroundWaiter.java:29)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]: 	at net.minecraft.client.main.Main.main(Main.java:123)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]: 	... 16 more
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at net.minecraft.block.Blocks.<clinit>(Blocks.java:30)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at net.minecraft.world.gen.surfacebuilders.SurfaceBuilder.<clinit>(SurfaceBuilder.java:12)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at net.minecraft.world.gen.surfacebuilders.ConfiguredSurfaceBuilders.<clinit>(SourceFile:11)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at net.minecraft.util.registry.WorldGenRegistries.func_243674_g(WorldGenRegistries.java:33)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at net.minecraft.util.registry.WorldGenRegistries.func_243668_a(WorldGenRegistries.java:89)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at net.minecraft.util.registry.WorldGenRegistries.<clinit>(WorldGenRegistries.java:88)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at net.minecraft.util.registry.Registry.<clinit>(Registry.java:464)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:38)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at net.minecraft.client.main.Main.lambda$main$0(Main.java:123)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [tweakeroo.mixins.json:MixinWorld] from phase [DEFAULT] in config [tweakeroo.mixins.json] FAILED during APPLY
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:636)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:588)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	... 25 more
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field unloadedBlockEntities was not located in the target class net.minecraft.world.World. Using refmap Tweakerge-refmap.json
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:629)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:305)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:280)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1288)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[247��2023 21:03:28.956] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	... 25 more
```

**Comment by iconFehu** [comment]
同样的报错信息
